server {
    listen 80;
    server_name localhost
    charset utf-8;
    root /var/www/public/;
    index index.html index.php;

    client_max_body_size 100M;
    client_body_buffer_size 128k;

    location /sqladmin {
        alias /var/www/database/sqladmin/;
        index index.php;

        location ~ ^/sqladmin/(.+\.php)$ {
            include fastcgi_params;
            fastcgi_pass harbour-php:9000;
            fastcgi_index index.php;

            fastcgi_param SCRIPT_FILENAME /var/www/database/sqladmin/$1;
            fastcgi_param SERVER_NAME $host;
            fastcgi_param HTTP_HOST $host;
            fastcgi_param SERVER_PORT 80;
        }
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass harbour-php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    rewrite ^/(.*)/$ /$1 permanent;
}
