[group:main]
programs=queue-worker

[program:queue-worker]
command=php /var/www/artisan queue:work --queue=scout,default
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
